"""Aday göstergeler. discover_tr.py bunları çeker, Türkiye filtresinden ve
hareket eleğinden geçirir. Buradaki her satır 'aday'dır, 'konu' değil —
konu listesi topics_tr.json'dur (script üretir).

Alanlar: kod, Türkçe gösterge adı (başlığa girer), bottom_ok (en düşük 10
formatı üretilsin mi — Türkiye'nin kötü göründüğü göstergelerde False).
"""

# ---------------------------------------------------------------- World Bank
# (kod, başlık, bottom_ok)
WB = [
    # --- Ekonomi
    ("NY.GDP.MKTP.CD",      "Milli Gelir (GSYH)",                      False),
    ("NY.GDP.PCAP.CD",      "Kişi Başına Milli Gelir",                 False),
    ("NY.GDP.MKTP.PP.CD",   "Satın Alma Gücüne Göre Milli Gelir",       False),
    ("NY.GDP.PCAP.PP.CD",   "Satın Alma Gücüne Göre Kişi Başı Gelir",   False),
    ("NY.GDP.MKTP.KD.ZG",   "Ekonomik Büyüme Hızı",                    False),
    ("NE.EXP.GNFS.CD",      "İhracat",                                 False),
    ("NE.IMP.GNFS.CD",      "İthalat",                                 False),
    ("TX.VAL.MRCH.CD.WT",   "Mal İhracatı",                            False),
    ("TM.VAL.MRCH.CD.WT",   "Mal İthalatı",                            False),
    ("BX.KLT.DINV.CD.WD",   "Yabancı Yatırım Girişi",                  False),
    ("BX.TRF.PWKR.CD.DT",   "Yurt Dışından Gelen İşçi Dövizi",         False),
    ("FI.RES.TOTL.CD",      "Altın ve Döviz Rezervi",                  False),
    ("NV.IND.MANF.CD",      "Sanayi Üretimi (İmalat)",                 False),
    ("NV.AGR.TOTL.CD",      "Tarımsal Üretim Değeri",                  False),
    ("NE.GDI.TOTL.CD",      "Toplam Yatırım Harcaması",                False),
    ("FP.CPI.TOTL.ZG",      "Enflasyon",                               False),
    ("SL.UEM.TOTL.ZS",      "İşsizlik Oranı",                          False),
    ("SL.TLF.TOTL.IN",      "İş Gücü (Çalışan Nüfus)",                 False),
    ("CM.MKT.LCAP.CD",      "Borsa Değeri",                            False),
    ("CM.MKT.LDOM.NO",      "Borsada İşlem Gören Şirket Sayısı",       False),
    ("FS.AST.PRVT.GD.ZS",   "Özel Sektöre Verilen Kredi (GSYH'ye Oranı)", False),
    ("GC.TAX.TOTL.GD.ZS",   "Vergi Gelirleri (GSYH'ye Oranı)",         False),
    ("TX.VAL.TECH.CD",      "Yüksek Teknoloji İhracatı",               False),
    ("TX.VAL.AGRI.ZS.UN",   "Tarım Ürünleri İhracat Payı",             False),
    ("TX.VAL.FUEL.ZS.UN",   "Yakıt İhracat Payı",                      False),
    ("TX.VAL.MANF.ZS.UN",   "Sanayi Ürünleri İhracat Payı",            False),
    # --- Savunma
    ("MS.MIL.XPND.CD",      "Askeri Harcama",                          False),
    ("MS.MIL.XPND.GD.ZS",   "Askeri Harcamanın Milli Gelire Oranı",    False),
    ("MS.MIL.XPND.ZS",      "Askeri Harcamanın Bütçeye Oranı",         False),
    # --- Nüfus
    ("SP.POP.TOTL",         "Nüfus",                                   True),
    ("SP.URB.TOTL",         "Şehirde Yaşayan Nüfus",                   True),
    ("SP.RUR.TOTL",         "Köyde Yaşayan Nüfus",                     True),
    ("SP.URB.TOTL.IN.ZS",   "Şehirleşme Oranı",                        True),
    ("SP.POP.GROW",         "Nüfus Artış Hızı",                        True),
    ("EN.POP.DNST",         "Nüfus Yoğunluğu",                         True),
    ("EN.URB.LCTY",         "En Büyük Şehrin Nüfusu",                  False),
    ("SP.DYN.LE00.IN",      "Ortalama Yaşam Süresi",                   True),
    ("SP.DYN.TFRT.IN",      "Doğurganlık Hızı",                        True),
    ("SP.DYN.CBRT.IN",      "Doğum Oranı",                             True),
    ("SP.POP.65UP.TO.ZS",   "65 Yaş Üstü Nüfus Oranı",                 True),
    ("SP.POP.0014.TO.ZS",   "Çocuk Nüfus Oranı (0-14)",                True),
    ("SM.POP.TOTL",         "Göçmen Nüfusu",                           False),
    ("SM.POP.REFG",         "Barındırılan Mülteci Sayısı",             False),
    ("SM.POP.NETM",         "Net Göç",                                 False),
    # --- Turizm
    ("ST.INT.ARVL",         "Turist Sayısı",                           False),
    ("ST.INT.RCPT.CD",      "Turizm Geliri",                           False),
    ("ST.INT.DPRT",         "Yurt Dışına Çıkan Turist Sayısı",         False),
    ("ST.INT.XPND.CD",      "Yurt Dışı Turizm Harcaması",              False),
    # --- Teknoloji
    ("IT.NET.USER.ZS",      "İnternet Kullanım Oranı",                 True),
    ("IT.CEL.SETS",         "Cep Telefonu Aboneliği",                  False),
    ("IT.CEL.SETS.P2",      "100 Kişiye Düşen Cep Telefonu",           True),
    ("IT.NET.BBND",         "Sabit Geniş Bant Aboneliği",              False),
    ("IT.NET.SECR",         "Güvenli İnternet Sunucusu Sayısı",        False),
    ("IP.PAT.RESD",         "Patent Başvurusu",                        False),
    ("IP.JRN.ARTC.SC",      "Bilimsel Makale Sayısı",                  False),
    ("GB.XPD.RSDV.GD.ZS",   "Ar-Ge Harcaması (GSYH'ye Oranı)",         False),
    ("SP.POP.SCIE.RD.P6",   "Milyon Kişiye Düşen Araştırmacı",         False),
    ("BX.GSR.CCIS.CD",      "Bilişim Hizmeti İhracatı",                False),
    # --- Enerji & Çevre
    ("EG.USE.PCAP.KG.OE",   "Kişi Başı Enerji Tüketimi",               True),
    ("EG.ELC.PROD.KH",      "Elektrik Üretimi",                        False),
    ("EG.USE.ELEC.KH.PC",   "Kişi Başı Elektrik Tüketimi",             True),
    ("EG.FEC.RNEW.ZS",      "Yenilenebilir Enerji Payı",               True),
    ("EG.ELC.RNEW.ZS",      "Yenilenebilir Elektrik Payı",             True),
    ("EG.ELC.HYRO.ZS",      "Hidroelektrik Payı",                      True),
    ("EG.IMP.CONS.ZS",      "Enerji İthalatına Bağımlılık",            True),
    ("EN.GHG.CO2.MT.CE.AR5","Karbon Emisyonu",                         True),
    ("EN.GHG.CO2.PC.CE.AR5","Kişi Başı Karbon Emisyonu",               True),
    ("AG.LND.FRST.K2",      "Orman Alanı",                             False),
    ("AG.LND.FRST.ZS",      "Orman Oranı",                             True),
    ("AG.LND.AGRI.K2",      "Tarım Alanı",                             False),
    ("AG.LND.ARBL.HA",      "Ekilebilir Arazi",                        False),
    ("AG.PRD.CREL.MT",      "Tahıl Üretimi",                           False),
    ("AG.LND.CREL.HA",      "Tahıl Ekim Alanı",                        False),
    ("AG.YLD.CREL.KG",      "Hektar Başına Tahıl Verimi",              True),
    ("ER.H2O.FWTL.K3",      "Tatlı Su Tüketimi",                       False),
    ("AG.LND.IRIG.AG.ZS",   "Sulanan Tarım Arazisi Oranı",             True),
    # --- Sağlık
    ("SH.XPD.CHEX.PC.CD",   "Kişi Başı Sağlık Harcaması",              True),
    ("SH.XPD.CHEX.GD.ZS",   "Sağlık Harcamasının Milli Gelire Oranı",  True),
    ("SH.MED.PHYS.ZS",      "1000 Kişiye Düşen Doktor",                True),
    ("SH.MED.BEDS.ZS",      "1000 Kişiye Düşen Hastane Yatağı",        True),
    ("SP.DYN.IMRT.IN",      "Bebek Ölüm Hızı",                         True),
    ("SH.DYN.MORT",         "5 Yaş Altı Ölüm Hızı",                    True),
    # --- Eğitim
    ("SE.XPD.TOTL.GD.ZS",   "Eğitim Harcamasının Milli Gelire Oranı",  True),
    ("SE.TER.ENRR",         "Üniversiteye Kayıt Oranı",                True),
    ("SE.SEC.ENRR",         "Liseye Kayıt Oranı",                      True),
    ("SE.ADT.LITR.ZS",      "Okuma Yazma Oranı",                       True),
    ("SE.PRM.ENRR",         "İlkokula Kayıt Oranı",                    True),
    # --- Ulaşım & Altyapı
    ("IS.AIR.PSGR",         "Hava Yolu Yolcu Sayısı",                  False),
    ("IS.AIR.DPRT",         "Uçak Kalkış Sayısı",                      False),
    ("IS.AIR.GOOD.MT.K1",   "Hava Kargo",                              False),
    ("IS.SHP.GOOD.TU",      "Liman Konteyner Trafiği",                 False),
    ("IS.RRS.TOTL.KM",      "Demir Yolu Uzunluğu",                     False),
    ("IS.RRS.PASG.KM",      "Demir Yolu Yolcu Taşıması",               False),
    ("IS.RRS.GOOD.MT.K6",   "Demir Yolu Yük Taşıması",                 False),
    # --- Toplum
    ("SG.GEN.PARL.ZS",      "Meclisteki Kadın Oranı",                  True),
    ("SL.TLF.CACT.FE.ZS",   "Kadın İstihdam Oranı",                    True),
    ("SI.POV.GINI",         "Gelir Eşitsizliği (Gini)",                True),
    ("SL.EMP.TOTL.SP.ZS",   "İstihdam Oranı",                          True),
    ("SP.DYN.LE00.FE.IN",   "Kadınlarda Yaşam Süresi",                 True),
    ("SP.DYN.LE00.MA.IN",   "Erkeklerde Yaşam Süresi",                 True),
]

# ---------------------------------------------------------------- OWID grapher
# Slug -> Türkçe başlık. Her slug ourworldindata.org/grapher/<slug>.csv'den
# çekilir. Slug'lar KESİN DEĞİL — discover_tr.py 404 verenleri raporlar,
# doğru slug'ı OWID'de aratıp buraya yazarsın.
OWID = [
    # --- Tarım (FAO verisi, OWID üzerinden — bozuk FAO API'sine gerek yok)
    ("wheat-production",                     "Buğday Üretimi"),
    ("barley-production",                    "Arpa Üretimi"),
    ("maize-production",                     "Mısır Üretimi"),
    ("rice-production",                      "Pirinç Üretimi"),
    ("potato-production",                    "Patates Üretimi"),
    ("tomato-production",                    "Domates Üretimi"),
    ("apple-production",                     "Elma Üretimi"),
    ("grape-production",                     "Üzüm Üretimi"),
    ("orange-production",                    "Portakal Üretimi"),
    ("banana-production",                    "Muz Üretimi"),
    ("olive-production",                     "Zeytin Üretimi"),
    ("tea-production",                       "Çay Üretimi"),
    ("coffee-bean-production",               "Kahve Üretimi"),
    ("cocoa-bean-production",                "Kakao Üretimi"),
    ("sugar-cane-production",                "Şeker Kamışı Üretimi"),
    ("sugar-beet-production",                "Şeker Pancarı Üretimi"),
    ("sunflower-seed-production",            "Ayçiçeği Üretimi"),
    ("cotton-production",                    "Pamuk Üretimi"),
    ("tobacco-production",                   "Tütün Üretimi"),
    ("lemon-production",                     "Limon Üretimi"),
    ("cherry-production",                    "Kiraz Üretimi"),
    ("apricot-production",                   "Kayısı Üretimi"),
    ("fig-production",                       "İncir Üretimi"),
    ("hazelnut-production",                  "Fındık Üretimi"),
    ("pistachio-production",                 "Antep Fıstığı Üretimi"),
    ("walnut-production",                    "Ceviz Üretimi"),
    ("almond-production",                    "Badem Üretimi"),
    ("chickpea-production",                  "Nohut Üretimi"),
    ("lentil-production",                    "Mercimek Üretimi"),
    ("watermelon-production",                "Karpuz Üretimi"),
    ("cucumber-production",                  "Salatalık Üretimi"),
    ("pepper-production",                    "Biber Üretimi"),
    ("onion-production",                     "Soğan Üretimi"),
    ("honey-production",                     "Bal Üretimi"),
    ("egg-production-thousand-tonnes",       "Yumurta Üretimi"),
    ("milk-production-tonnes",               "Süt Üretimi"),
    ("meat-production-tonnes",               "Et Üretimi"),
    ("chicken-meat-production",              "Tavuk Eti Üretimi"),
    ("beef-and-buffalo-meat-production-tonnes", "Sığır Eti Üretimi"),
    ("sheep-and-goat-meat-production",       "Koyun-Keçi Eti Üretimi"),
    ("number-of-cattle",                     "Sığır Sayısı"),
    ("number-of-sheep",                      "Koyun Sayısı"),
    ("number-of-goats",                      "Keçi Sayısı"),
    ("number-of-chickens",                   "Tavuk Sayısı"),
    ("capture-fishery-production",           "Balıkçılık Üretimi"),
    ("aquaculture-production",               "Kültür Balıkçılığı Üretimi"),
    # --- Enerji & sanayi
    ("electricity-generation",               "Elektrik Üretimi"),
    ("primary-energy-cons",                  "Toplam Enerji Tüketimi"),
    ("solar-energy-consumption",             "Güneş Enerjisi Üretimi"),
    ("wind-generation",                      "Rüzgar Enerjisi Üretimi"),
    ("hydropower-consumption",               "Hidroelektrik Üretimi"),
    ("geothermal-energy-generation",         "Jeotermal Enerji Üretimi"),
    ("coal-production-by-country",           "Kömür Üretimi"),
    ("oil-production-by-country",            "Petrol Üretimi"),
    ("gas-production-by-country",            "Doğal Gaz Üretimi"),
    ("coal-consumption-by-country-terawatt-hours", "Kömür Tüketimi"),
    ("oil-consumption-by-country",           "Petrol Tüketimi"),
    ("gas-consumption-by-country",           "Doğal Gaz Tüketimi"),
    ("steel-production",                     "Çelik Üretimi"),
    ("cement-production",                    "Çimento Üretimi"),
    ("annual-co2-emissions-per-country",     "Karbon Emisyonu"),
    # --- Savunma & toplum
    ("military-expenditure-total",           "Askeri Harcama"),
    ("armed-forces-personnel",               "Asker Sayısı"),
    ("population",                           "Nüfus"),
    ("life-expectancy",                      "Ortalama Yaşam Süresi"),
    ("human-development-index",              "İnsani Gelişme Endeksi"),
    ("gdp-per-capita-maddison-project-database", "Kişi Başı Gelir (Tarihsel)"),
    ("number-of-internet-users",             "İnternet Kullanıcı Sayısı"),
    ("mobile-cellular-subscriptions-per-100-people", "100 Kişiye Düşen Cep Telefonu"),
    ("international-tourist-trips",          "Turist Sayısı"),
    ("passenger-cars-per-1000-inhabitants",  "1000 Kişiye Düşen Otomobil"),
    ("olympic-medals",                       "Olimpiyat Madalyası"),
    ("number-of-scientific-publications",    "Bilimsel Yayın Sayısı"),
]
